#!/bin/bash

# Define command-line arguments

NAMESPACE=kube-system
RESOURCE_TYPE=pod

if [ -z "$NAMESPACE" ] || [ -z "$RESOURCE_TYPE" ]; then
  echo "Usage: $0 <namespace> <resource_type>"
  echo "Example: $0 default pods"
  exit 1
fi

# Retrieve resource usage statistics from Kubernetes
#kubectl $2 $RESOURCE_TYPE -n $1 | tail -n +2 | while read line
#do
kubectl get $RESOURCE_TYPE -n  $NAMESPACE | tail -n +2 | while read line; 
do	
  # Extract CPU and memory usage from the output
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')
  MEMORY=$(echo $line | awk '{print $3}')

  # Output the statistics to the console
  # "Resource, Namespace, Name, CPU, Memory"
  echo "Resource: $RESOURCE_TYPE, Namespace: $NAMESPACE, Name: $NAME, CPU: $CPU, Memory: $MEMORY"
done
